### ISSUE TITLE
Gnome 43 Support

### ISSUE THREAD

**Issue by ghost** [codilia/upower-battery#4]
Hi Codilia,

I am currently using your extension and like it a lot and I would like to continue using it with Gnome 43. Will the extension support Gnome 43 in the future and are there patches planned for it?

**Comment by ppiastucki** [comment]
Hey,
Thanks for your feedback. Yes, definitely the extension will support Gnome Shell 43. I have not tested it yet, but I think it should work out of the box. Have you encountered any problems? 
In order to test the extension with newer versions of Gnome Shell please just add them here: https://github.com/codilia/upower-battery/blob/main/metadata.json#L5 locally.

**Comment by ghost** [comment]
Okay, thank for your reply!

I will try that out when I upgrade to Fedora 37 which ships with Gnome 43.

**Comment by ghost** [comment]
Just wanted to say, that I switched to a different extension so I will likely not test this extension anymore.

**Comment by EmptyVisual** [comment]
@ppiastucki I've been using the extension on Gnome 43 for nearly a week and it's been working perfectly with no issues. Wonderful extension honestly, it's the only one that shows percentage indicators next to the icon.

I had to toggle "Disable version validation" on https://extensions.gnome.org/local/

But aside from that everything's good. I assume we are good in just bumping the version number?

**Comment by ppiastucki** [comment]
@EmptyVisual Thank you very much for the confirmation. I have just added Gnome 43 to supported versions.
